version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:1.4
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql:1.4
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  connect:
    image: debezium/connect:1.4
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  maxwell:
    image: zendesk/maxwell
    command: bin/maxwell --user=root --password=debezium --host=mysql --producer=kafka --kafka.bootstrap.servers=kafka:9092 --kafka_topic=maxwell --output_ddl=true
    depends_on:
      - mysql
      - zookeeper
      - kafka
    restart: always

  pinot:
    container_name: pinot
    image: apachepinot/pinot:0.6.0
    command: "QuickStart -type batch"
    links:
      - zookeeper
      - kafka
    ports:
      - '9000:9000'
      - '8000:8000'